// next/src/types/venue.ts

// Based on the VenueCard and API endpoints, define a comprehensive type
// This might need refinement as we implement more features
export interface Venue {
	id: string;
	name: string;
	description?: string; // Added optional description
	address: string; // Consider making this structured later (street, city, zip, etc.)
	latitude?: number;
	longitude?: number;
	phone?: string;
	website?: string;
	category?: { id?: string; name: string }; // Changed to object type
	mainPhotoUrl?: string;
	photos?: { id: string; url: string }[]; // For gallery
	rating?: number;
	status: VenueStatus; // Added for lifecycle management
	verified: boolean; // Added for verification status
	createdAt: string; // Assuming ISO string format from API
	updatedAt: string; // Assuming ISO string format from API
	// Add other fields as needed, e.g., opening hours, amenities, owner info
}

// Define possible venue statuses
export const venueStatuses = ['pending', 'active', 'inactive'] as const;
export type VenueStatus = typeof venueStatuses[number];

// Type for the search API response (assuming pagination)
export interface VenueSearchResult {
	venues: Venue[];
	total: number;
	page: number;
	limit: number;
}

// Type for search parameters
export interface VenueSearchParams {
	query?: string; // General search term (could search name, category, etc.)
	name?: string;
	location?: string; // Could be city, address fragment, etc.
	category?: string;
	page?: number;
	limit?: number;
	sortBy?: string; // e.g., 'rating', 'name', 'createdAt'
	sortOrder?: 'asc' | 'desc';
}

// --- Added Venue Settings & Staff Types ---

export interface BusinessHour {
	dayOfWeek: number; // 0 for Sunday, 1 for Monday, ..., 6 for Saturday
	openTime: string; // HH:mm format
	closeTime: string; // HH:mm format
	isOpen: boolean;
}

export interface BookingSettings {
	enabled: boolean;
	requireApproval: boolean;
	allowCancellation: boolean;
	cancellationPolicy?: string; // Optional policy text
}

export interface LoyaltyProgramSettings {
	enabled: boolean;
	pointsPerVisit?: number; // Optional based on program type
	rewardThreshold?: number; // Optional based on program type
	rewardDescription?: string; // Optional based on program type
}

export interface AffiliateProgramSettings {
	enabled: boolean;
	commissionRate?: number; // Percentage, optional
	cookieDuration?: number; // Days, optional
}

export interface VenueSettings {
	// id: string; // Settings might not have their own ID, they belong to a venue
	businessHours: BusinessHour[];
	bookingSettings: BookingSettings;
	loyaltyProgram: LoyaltyProgramSettings;
	affiliateProgram: AffiliateProgramSettings;
	currency: string; // e.g., 'USD', 'EUR'
	timezone: string; // e.g., 'America/New_York', 'Europe/London'
	venueId: string;
	createdAt?: string; // Optional if not always returned
	updatedAt?: string; // Optional if not always returned
}

// Define as a const tuple for Zod enum compatibility
export const staffRoles = ['owner', 'manager', 'staff', 'hostess', 'waiter', 'bartender'] as const;
// Infer the union type from the tuple
export type StaffRole = typeof staffRoles[number];


export interface StaffMember {
	id: string; // This is the VenueStaff ID, not the User ID
	userId: string;
	venueId: string;
	email: string; // Assuming we get email for display
	name: string; // Assuming we get name for display
	role: StaffRole;
	// permissions?: string[]; // Add if permissions are more granular than roles
	joinedAt: string; // Assuming ISO string format
	// Add other relevant user details if needed (e.g., profile picture URL)
	user?: { // Embed user details if API provides them
		id: string;
		name: string;
		email: string;
		avatarUrl?: string;
	}
}

// --- Add CreateVenueData and UpdateVenueData Types ---
// Type for creating a venue (adjust based on API requirements)
// Exclude fields generated by the backend (id, timestamps, maybe rating, photos initially, status, verified)
// Assume status defaults to 'pending' and verified defaults to 'false' on backend during creation.
export type CreateVenueData = Omit<Venue, 'id' | 'createdAt' | 'updatedAt' | 'rating' | 'photos' | 'mainPhotoUrl' | 'status' | 'verified'> & {
	// Add any specific fields required only on creation, if any
};

// Type for updating a venue (allow partial updates)
// Allow updating status and verified status
export type UpdateVenueData = Partial<Omit<CreateVenueData, 'status'> & {
	status?: VenueStatus;
	verified?: boolean;
}>;


// DTOs for API requests

export interface AddStaffDto {
	email: string; // Backend finds user by email
	role: StaffRole;
}

export interface UpdateStaffDto {
	role?: StaffRole;
	// permissions?: string[]; // Add if API supports updating permissions directly
}

export interface UpdateVenueSettingsDto {
	businessHours?: BusinessHour[];
	bookingSettings?: Partial<BookingSettings>;
	loyaltyProgram?: Partial<LoyaltyProgramSettings>;
	affiliateProgram?: Partial<AffiliateProgramSettings>;
	currency?: string;
	timezone?: string;
}

export interface TransferOwnershipDto {
	newOwnerEmail: string; // Easier to identify user by email on frontend
}

// --- Venue Table Types ---

export const tableTypes = [
	'standard',
	'bar',
	'private',
	'outdoor',
	'lounge',
	'vip',
] as const;
export type TableType = (typeof tableTypes)[number];

export const tableStatuses = [
	'available',
	'occupied',
	'reserved',
	'out_of_service',
] as const;
export type TableStatus = (typeof tableStatuses)[number];

// Matches the backend TableResponseDTO
export interface Table {
	id: string;
	venueId: string; // Renamed from venue_id
	name: string;
	capacity: number;
	type: TableType;
	location: string; // Now required? Backend shows optionality inconsistency
	status: TableStatus;
	minimumSpend: number | null; // Renamed & nullable
	description: string | null; // Nullable
	isActive: boolean; // Added
	positionX: number | null; // Added & nullable
	positionY: number | null; // Added & nullable
	groupId: string | null; // Added & nullable (UUID becomes string)
	qrCode: string | null; // Added & nullable
	createdAt: string; // Renamed from created_at
	updatedAt: string; // Renamed from updated_at
}

// DTOs for Table API requests
export interface CreateTableDto {
	name: string;
	capacity: number;
	type: TableType;
	location?: string;
	status?: TableStatus; // Optional on create (defaults to available)
	minimumSpend?: number; // Renamed & optional
	description?: string;
	isActive?: boolean; // Added & optional
	positionX?: number; // Added & optional
	positionY?: number; // Added & optional
	groupId?: string; // Added & optional (UUID string)
}

export interface UpdateTableDto {
	name?: string;
	capacity?: number;
	type?: TableType;
	location?: string;
	status?: TableStatus;
	minimumSpend?: number; // Renamed & optional
	description?: string;
	isActive?: boolean; // Added & optional
	positionX?: number; // Added & optional
	positionY?: number; // Added & optional
	groupId?: string; // Added & optional (UUID string)
}

// Type for the Get Tables API response (matches API)
export interface VenueTableListResponse {
	tables: Table[]; // Use the updated Table type
	total: number;
	page: number;
	limit: number;
}

// Type for Table search/filter parameters (if needed for client-side or API filtering)
export interface TableFilterParams {
	status?: TableStatus;
	location?: string;
	type?: TableType;
	// Add other potential filter fields
}
