import type {Metadata} from 'next'
import {Geist, Geist_Mono} from 'next/font/google'
import './globals.css'
import {AuthProvider} from '@/components/providers/AuthProvider'
import {AuthStatus} from '@/components/auth/AuthStatus'
import {ThemeProvider} from '@/components/providers/theme-provider'
import {ModeToggle} from '@/components/ui/mode-toggle'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ThemeProvider attribute='class' defaultTheme='dark' enableSystem disableTransitionOnChange>
					<AuthProvider>
						<header className='fixed top-0 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60'>
							<div className='container flex h-14 max-w-screen-2xl items-center justify-between'>
								<AuthStatus />
								<ModeToggle />
							</div>
						</header>
						<main className='pt-16'>{children}</main>
					</AuthProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
